name: CI

on: [push, pull_request]

jobs:
  python:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        python-version: ["3.7", "3.8", "3.9", "3.10", "3.11", "3.12"]

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          architecture: x64
          cache: "pip"

      - name: Install Poetry manager
        run: pip install --upgrade poetry

      - name: Install Dependencies
        run: poetry install

      - name: Test with pytest
        run: |
          poetry run pytest --cov=transloadit tests
